# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reg2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_MainWindow(object):
    def conn(self):
        from newdesigne import Ui_MainWindow1
        self.ui = Ui_MainWindow1()
        self.ui.setupUi(MainWindow)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(438, 418)
        MainWindow.setAcceptDrops(True)
        MainWindow.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(-6, -8, 221, 131))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"\n"
"border: 0 px;\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"}\n"
".QPushButton:hover{\n"
"background-color:rgb(216, 216, 216);\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(214, -8, 231, 131))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"\n"
"border: 0 px;\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"\n"
"}\n"
"\n"
".QPushButton:hover{\n"
"background-color:rgb(216, 216, 216);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 210, 271, 31))
        self.label.setStyleSheet("QLabel{\n"
"\n"
"border-top-left-radius:10%;\n"
"border-top-right-radius:10%;\n"
"border-bottom-left-radius:10%;\n"
"border-bottom-right-radius:10%;\n"
"background-color: rgb(85, 0, 255);\n"
"\n"
"}")
        self.label.setLineWidth(0)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("padlock.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 160, 271, 31))
        self.label_2.setStyleSheet("QLabel{\n"
"\n"
"border-top-left-radius:10%;\n"
"border-top-right-radius:10%;\n"
"border-bottom-left-radius:10%;\n"
"border-bottom-right-radius:10%;\n"
"background-color: rgb(85, 0, 255);\n"
"\n"
"}")
        self.label_2.setLineWidth(0)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("padlock.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 270, 271, 31))
        self.label_3.setStyleSheet("QLabel{\n"
"\n"
"border-top-left-radius:10%;\n"
"border-top-right-radius:10%;\n"
"border-bottom-left-radius:10%;\n"
"border-bottom-right-radius:10%;\n"
"background-color: rgb(85, 0, 255);\n"
"\n"
"}")
        self.label_3.setLineWidth(0)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("padlock.png"))
        self.label_3.setObjectName("label_3")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(90, 320, 91, 17))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setGeometry(QtCore.QRect(80, 360, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color:rgb(85, 0, 255);\n"
"border-top-left-radius: 10%;\n"
"border-top-right-radius: 10%;\n"
"border-bottom-left-radius: 10%;\n"
"border-bottom-right-radius: 10%;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.conn)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Sing in"))
        self.pushButton_2.setText(_translate("MainWindow", "New account"))
        self.checkBox.setText(_translate("MainWindow", "Private Police"))
        self.pushButton_3.setText(_translate("MainWindow", "login"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
